// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200311074349_Backend")]
    partial class Backend
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fundoo.Model.RegisterModel", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("Id");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Email");

                    b.ToTable("registers");
                });

            modelBuilder.Entity("Model.Model.Collaborators.CollaboratorModel", b =>
                {
                    b.Property<string>("SenderEmail")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NoteId");

                    b.Property<string>("ReceiverEmail");

                    b.HasKey("SenderEmail");

                    b.ToTable("collaborators");
                });

            modelBuilder.Entity("Model.Model.LabelModel.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelName");

                    b.Property<int>("Noteid");

                    b.HasKey("LabelId");

                    b.ToTable("labels");
                });

            modelBuilder.Entity("Model.Model.NodesModel.Nodes", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddImg");

                    b.Property<bool>("Archive");

                    b.Property<string>("ChangeColor");

                    b.Property<DateTime?>("Createdate1");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("Modifieddate");

                    b.Property<bool>("Pin");

                    b.Property<string>("Tittle");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
